=== anilsaldhana/picketlink-idm/1.1.0/picketlink-idm-testsuite/src/test/resources/identity-config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
           targetNamespace="urn:picketlink:idm:config:v1_0_0_ga" xmlns:xs="http://www.w3.org/2001/XMLSchema">
   <xs:element name="jboss-identity" type="urn:jboss-identityType" xmlns:urn="urn:picketlink:idm:config:v1_0_0_ga">
      <xs:annotation>
         <xs:documentation>&lt;xs:schemaattributeFormDefault="unqualified"elementFormDefault="qualified"xmlns:xs="http://www.w3.org/2001/XMLSchema"targetNamespace="urn:picketlink:idm:config:v1_0_0_ga"xmlns="urn:picketlink:idm:config:v1_0_0_ga"xmlns:xml="http://www.w3.org/XML/1998/namespace"xmlns:wcc="urn:picketlink:idm:config:v1_0_0_ga"></xs:documentation>
      </xs:annotation>
   </xs:element>
   <xs:complexType name="identity-object-typesType">
      <xs:sequence>
         <xs:element type="xs:string" name="identity-object-type" maxOccurs="unbounded" minOccurs="0"/>
      </xs:sequence>
   </xs:complexType>
   <xs:complexType name="repositoryType">
      <xs:sequence>
         <xs:element type="xs:string" name="id"/>
         <xs:element type="xs:string" name="class"/>
         <xs:element type="urn:external-configType" name="external-config" minOccurs="0"
                     xmlns:urn="urn:picketlink:idm:config:v1_0_0_ga"/>
         <xs:element type="xs:string" name="default-identity-store-id" minOccurs="0"/>
         <xs:element type="xs:string" name="default-attribute-store-id" minOccurs="0"/>
         <xs:element type="urn:identity-store-mappingsType" name="identity-store-mappings" minOccurs="0"
                     xmlns:urn="urn:picketlink:idm:config:v1_0_0_ga"/>
         <xs:element type="urn:optionsType" name="options" minOccurs="0"
                     xmlns:urn="urn:picketlink:idm:config:v1_0_0_ga"/>
      </xs:sequence>
   </xs:complexType>
   <xs:complexType name="identity-storeType">
      <xs:sequence>
         <xs:element type="xs:string" name="id"/>
         <xs:element type="xs:string" name="class"/>
         <xs:element type="urn:external-configType" name="external-config"
                     xmlns:urn="urn:picketlink:idm:config:v1_0_0_ga"/>
         <xs:element type="urn:supported-relationship-typesType" name="supported-relationship-types"
                     xmlns:urn="urn:picketlink:idm:config:v1_0_0_ga"/>
         <xs:element type="urn:supported-identity-object-typesType" name="supported-identity-object-types"
                     xmlns:urn="urn:picketlink:idm:config:v1_0_0_ga"/>
         <xs:element name="options">
            <xs:complexType>
               <xs:sequence>
                  <xs:element type="urn:optionType" name="option" maxOccurs="unbounded" minOccurs="0"
                              xmlns:urn="urn:picketlink:idm:config:v1_0_0_ga"/>
               </xs:sequence>
            </xs:complexType>
         </xs:element>
      </xs:sequence>
   </xs:complexType>
   <xs:complexType name="external-configType">
      <xs:simpleContent>
         <xs:extension base="xs:string">
            <xs:attribute type="xs:string" name="override" use="optional"/>
         </xs:extension>
      </xs:simpleContent>
   </xs:complexType>
   <xs:complexType name="identity-store-mappingsType">
      <xs:sequence>
         <xs:element type="urn:identity-store-mappingType" name="identity-store-mapping" maxOccurs="unbounded"
                     minOccurs="0" xmlns:urn="urn:picketlink:idm:config:v1_0_0_ga"/>
      </xs:sequence>
   </xs:complexType>
   <xs:complexType name="storesType">
      <xs:sequence>
         <xs:element type="xs:string" name="attribute-stores"/>
         <xs:element type="urn:identity-storesType" name="identity-stores"
                     xmlns:urn="urn:picketlink:idm:config:v1_0_0_ga"/>
      </xs:sequence>
   </xs:complexType>
   <xs:complexType name="jboss-identityType">
      <xs:sequence>
         <xs:element type="urn:realmsType" name="realms" xmlns:urn="urn:picketlink:idm:config:v1_0_0_ga"/>
         <xs:element type="urn:repositoriesType" name="repositories" xmlns:urn="urn:picketlink:idm:config:v1_0_0_ga"/>
         <xs:element type="urn:storesType" name="stores" xmlns:urn="urn:picketlink:idm:config:v1_0_0_ga"/>
      </xs:sequence>
   </xs:complexType>
   <xs:complexType name="supported-identity-object-typesType">
      <xs:sequence>
         <xs:element type="urn:identity-object-typeType" name="identity-object-type" maxOccurs="unbounded" minOccurs="0"
                     xmlns:urn="urn:picketlink:idm:config:v1_0_0_ga"/>
      </xs:sequence>
   </xs:complexType>
   <xs:complexType name="optionType">
      <xs:sequence>
         <xs:element type="xs:string" name="name"/>
         <xs:element type="xs:string" name="value" maxOccurs="unbounded" minOccurs="0"/>
      </xs:sequence>
   </xs:complexType>
   <xs:complexType name="group-type-mappingType">
      <xs:sequence>
         <xs:element type="xs:string" name="group-type-name"/>
         <xs:element type="xs:string" name="identity-object-type-name"/>
      </xs:sequence>
   </xs:complexType>
   <xs:complexType name="credentialsType">
      <xs:sequence>
         <xs:element type="xs:string" name="credential-type" maxOccurs="unbounded" minOccurs="0"/>
      </xs:sequence>
   </xs:complexType>
   <xs:complexType name="repositoriesType">
      <xs:sequence>
         <xs:element type="urn:repositoryType" name="repository" maxOccurs="unbounded" minOccurs="0"
                     xmlns:urn="urn:picketlink:idm:config:v1_0_0_ga"/>
      </xs:sequence>
   </xs:complexType>
   <xs:complexType name="realmType">
      <xs:sequence>
         <xs:element type="xs:string" name="id"/>
         <xs:element type="xs:string" name="repository-id-ref"/>
         <xs:element type="urn:identity-type-mappingsType" name="identity-type-mappings" minOccurs="0"
                     xmlns:urn="urn:picketlink:idm:config:v1_0_0_ga"/>
         <xs:element type="urn:optionsType" name="options" minOccurs="0"
                     xmlns:urn="urn:picketlink:idm:config:v1_0_0_ga"/>
      </xs:sequence>
   </xs:complexType>
   <xs:complexType name="relationshipsType">
      <xs:sequence>
         <xs:element type="urn:relationshipType" name="relationship" maxOccurs="unbounded" minOccurs="0"
                     xmlns:urn="urn:picketlink:idm:config:v1_0_0_ga"/>
      </xs:sequence>
   </xs:complexType>
   <xs:complexType name="realmsType">
      <xs:sequence>
         <xs:element type="urn:realmType" name="realm" maxOccurs="unbounded" minOccurs="0"
                     xmlns:urn="urn:picketlink:idm:config:v1_0_0_ga"/>
      </xs:sequence>
   </xs:complexType>
   <xs:complexType name="identity-type-mappingsType">
      <xs:sequence>
         <xs:element type="xs:string" name="user-mapping"/>
         <xs:element type="urn:group-type-mappingType" name="group-type-mapping" maxOccurs="unbounded" minOccurs="0"
                     xmlns:urn="urn:picketlink:idm:config:v1_0_0_ga"/>
      </xs:sequence>
   </xs:complexType>
   <xs:complexType name="supported-relationship-typesType">
      <xs:sequence>
         <xs:element type="xs:string" name="relationship-type" maxOccurs="unbounded" minOccurs="0"/>
      </xs:sequence>
   </xs:complexType>
   <xs:complexType name="identity-storesType">
      <xs:sequence>
         <xs:element type="urn:identity-storeType" name="identity-store" maxOccurs="unbounded" minOccurs="0"
                     xmlns:urn="urn:picketlink:idm:config:v1_0_0_ga"/>
      </xs:sequence>
   </xs:complexType>
   <xs:complexType name="attributesType">
      <xs:sequence>
         <xs:element type="urn:attributeType" name="attribute" maxOccurs="unbounded" minOccurs="0"
                     xmlns:urn="urn:picketlink:idm:config:v1_0_0_ga"/>
      </xs:sequence>
   </xs:complexType>
   <xs:complexType name="identity-store-mappingType">
      <xs:sequence>
         <xs:element type="xs:string" name="identity-store-id"/>
         <xs:element type="urn:identity-object-typesType" name="identity-object-types"
                     xmlns:urn="urn:picketlink:idm:config:v1_0_0_ga"/>
         <xs:element type="urn:optionsType" name="options" xmlns:urn="urn:picketlink:idm:config:v1_0_0_ga"/>
      </xs:sequence>
   </xs:complexType>
   <xs:complexType name="relationshipType">
      <xs:sequence>
         <xs:element type="xs:string" name="relationship-type-ref"/>
         <xs:element type="xs:string" name="identity-object-type-ref"/>
      </xs:sequence>
   </xs:complexType>
   <xs:complexType name="optionsType">
      <xs:sequence>
         <xs:element type="urn:optionType" name="option" maxOccurs="unbounded" minOccurs="0"
                     xmlns:urn="urn:picketlink:idm:config:v1_0_0_ga"/>
      </xs:sequence>
   </xs:complexType>
   <xs:complexType name="identity-object-typeType">
      <xs:sequence>
         <xs:element type="xs:string" name="name"/>
         <xs:element name="relationships">
            <xs:complexType>
               <xs:sequence>
                  <xs:element type="urn:relationshipType" name="relationship" maxOccurs="unbounded" minOccurs="0"
                              xmlns:urn="urn:picketlink:idm:config:v1_0_0_ga"/>
               </xs:sequence>
            </xs:complexType>
         </xs:element>
         <xs:element name="credentials">
            <xs:complexType>
               <xs:sequence>
                  <xs:element type="xs:string" name="credential-type" maxOccurs="unbounded" minOccurs="0"/>
               </xs:sequence>
            </xs:complexType>
         </xs:element>
         <xs:element name="attributes">
            <xs:complexType>
               <xs:sequence>
                  <xs:element type="urn:attributeType" name="attribute" maxOccurs="unbounded" minOccurs="0"
                              xmlns:urn="urn:picketlink:idm:config:v1_0_0_ga"/>
               </xs:sequence>
            </xs:complexType>
         </xs:element>
         <xs:element name="options">
            <xs:complexType>
               <xs:sequence>
                  <xs:element type="urn:optionType" name="option" maxOccurs="unbounded" minOccurs="0"
                              xmlns:urn="urn:picketlink:idm:config:v1_0_0_ga"/>
               </xs:sequence>
            </xs:complexType>
         </xs:element>
      </xs:sequence>
   </xs:complexType>
   <xs:complexType name="attributeType">
      <xs:sequence>
         <xs:element type="xs:string" name="name"/>
         <xs:element type="xs:string" name="mapping"/>
         <xs:element type="xs:string" name="type"/>
         <xs:element name="isRequired" minOccurs="0" maxOccurs="1">
            <xs:simpleType>
               <xs:restriction base="xs:string">
                  <xs:enumeration value="true"/>
                  <xs:enumeration value="false"/>
               </xs:restriction>
            </xs:simpleType>
         </xs:element>
         <xs:element name="isMultivalued" minOccurs="0">
            <xs:simpleType>
               <xs:restriction base="xs:string">
                  <xs:enumeration value="true"/>
                  <xs:enumeration value="false"/>
               </xs:restriction>
            </xs:simpleType>
         </xs:element>
         <xs:element type="xs:string" name="isReadOnly" minOccurs="0">
            <xs:simpleType>
               <xs:restriction base="xs:string">
                  <xs:enumeration value="true"/>
                  <xs:enumeration value="false"/>
               </xs:restriction>
            </xs:simpleType>
         </xs:element>
         <xs:element type="xs:string" name="isUnique" minOccurs="0">
            <xs:simpleType>
               <xs:restriction base="xs:string">
                  <xs:enumeration value="true"/>
                  <xs:enumeration value="false"/>
               </xs:restriction>
            </xs:simpleType>
         </xs:element>
      </xs:sequence>
   </xs:complexType>
</xs:schema>

=== anilsaldhana/picketlink-idm/picketlink-idm-memory/src/test/resources/configs/memory-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<jboss-identity xmlns="urn:picketlink:idm:config:v1_0_0_ga"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xsi:schemaLocation="urn:picketlink:idm:config:v1_0_0_ga identity-config.xsd">
    <realms>
        <realm>
            <id>realm://memory</id>
            <repository-id-ref>Memory based repo</repository-id-ref>
            <identity-type-mappings>
                <user-mapping>USER</user-mapping>
            </identity-type-mappings>
        </realm>
    </realms>
    <repositories>
        <repository>
            <id>Memory based repo</id>
            <class>org.picketlink.idm.impl.store.memory.MemoryIdentityStoreRepository</class>
            <external-config/>
            <default-identity-store-id>MemoryStore</default-identity-store-id>
            <default-attribute-store-id>MemoryStore</default-attribute-store-id>
            <!--<identity-store-mappings>-->
                <!--<identity-store-mapping>-->
                    <!--<identity-store-id>HibernateTestStore</identity-store-id>-->
                    <!--<identity-object-types/>-->
                    <!--<options/>-->
                <!--</identity-store-mapping>-->
            <!--</identity-store-mappings>-->
        </repository>
    </repositories>
    <stores>
        <attribute-stores/>
        <identity-stores>
            <identity-store>
                <id>MemoryStore</id>
                <class>org.picketlink.idm.impl.store.memory.MemoryIdentityStore</class>
                <external-config/>
                <supported-relationship-types>
                    <relationship-type>JBOSS_IDENTITY_MEMBERSHIP</relationship-type>
                    <relationship-type>JBOSS_IDENTITY_ROLE</relationship-type>
                </supported-relationship-types>
                <supported-identity-object-types>
                    <identity-object-type>
                        <name>USER</name>
                        <relationships/>
                        <credentials>
                            <credential-type>PASSWORD</credential-type>
                            <credential-type>BINARY</credential-type>
                        </credentials>
                        <attributes/>
                        <options/>
                    </identity-object-type>
                    <identity-object-type>
                        <name>GROUP</name>
                        <relationships/>
                        <credentials/>
                        <attributes/>
                        <options/>
                    </identity-object-type>
                    <identity-object-type>
                        <name>ORGANIZATION</name>
                        <relationships>
                            <relationship>
                                <relationship-type-ref>JBOSS_IDENTITY_MEMBERSHIP</relationship-type-ref>
                                <identity-object-type-ref>USER</identity-object-type-ref>
                            </relationship>
                            <relationship>
                                <relationship-type-ref>JBOSS_IDENTITY_MEMBERSHIP</relationship-type-ref>
                                <identity-object-type-ref>ROLE</identity-object-type-ref>
                            </relationship>
                            <relationship>
                                <relationship-type-ref>JBOSS_IDENTITY_MEMBERSHIP</relationship-type-ref>
                                <identity-object-type-ref>GROUP</identity-object-type-ref>
                            </relationship>
                            <relationship>
                                <relationship-type-ref>JBOSS_IDENTITY_MEMBERSHIP</relationship-type-ref>
                                <identity-object-type-ref>ORGANIZATION</identity-object-type-ref>
                            </relationship>
                        </relationships>
                        <credentials/>
                        <attributes/>
                        <options/>
                    </identity-object-type>
                    <identity-object-type>
                        <name>ROLE</name>
                        <relationships>
                            <relationship>
                                <relationship-type-ref>JBOSS_IDENTITY_MEMBERSHIP</relationship-type-ref>
                                <identity-object-type-ref>USER</identity-object-type-ref>
                            </relationship>
                        </relationships>
                        <credentials/>
                        <attributes/>
                        <options/>
                    </identity-object-type>
                </supported-identity-object-types>
                <options>
                    <!--<option>-->
                        <!--<name>hibernateConfiguration</name>-->
                        <!--<value>hibernate-jboss-identity.cfg.xml</value>-->
                    <!--</option>-->
                    <option>
                        <name>hibernateSessionFactoryJNDIName</name>
                        <value>java:/jbossidentity/HibernateStoreSessionFactory</value>
                    </option>
                    <option>
                        <name>populateRelationshipTypes</name>
                        <value>true</value>
                    </option>
                    <option>
                        <name>populateIdentityObjectTypes</name>
                        <value>true</value>
                    </option>
                    <option>
                        <name>isRealmAware</name>
                        <value>false</value>
                    </option>
                    <option>
                        <name>allowNotDefinedAttributes</name>
                        <value>true</value>
                    </option>
                </options>
            </identity-store>
        </identity-stores>
    </stores>
</jboss-identity>

=== anilsaldhana/picketlink-idm/1.1.0/picketlink-idm-core/src/test/resources/test-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<jboss-identity xmlns="urn:picketlink:idm:config:v1_0_0_ga"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xsi:schemaLocation="urn:picketlink:idm:config:v1_0_0_ga identity-config.xsd">
   <realms>
      <realm>
          <id>Sample Ralm</id>
          <repository-id-ref>Fallback Repository - ACME</repository-id-ref>
          <identity-type-mappings>
              <user-mapping>IDENTITY</user-mapping>
          </identity-type-mappings>
      </realm>
   </realms>
    <repositories>
        <repository>
            <id>Fallback Repository - ACME</id>
            <class>org.picketlink.idm.impl.repository.FallbackIdentityStoreRepository</class>
            <external-config override="false">path/to/file.xml</external-config>
            <default-identity-store-id>Hibernate Identity Store</default-identity-store-id>
            <default-attribute-store-id>Hibernate Identity Store</default-attribute-store-id>
            <identity-store-mappings>
                <identity-store-mapping>
                    <identity-store-id>Hibernate Identity Store</identity-store-id>
                    <identity-object-types>
                        <identity-object-type>JBOSS_IDENTITY_GROUP_ORGANIZATION</identity-object-type>
                        <identity-object-type>JBOSS_IDENTITY_GROUP_ORGANIZATION_UNIT</identity-object-type>
                        <identity-object-type>JBOSS_IDENTITY_GROUP_DIVISION</identity-object-type>
                        <identity-object-type>JBOSS_IDENTITY_GROUP_DEPARTMENT</identity-object-type>
                        <identity-object-type>JBOSS_IDENTITY_GROUP_PROJECT</identity-object-type>
                    </identity-object-types>
                    <options/>
                </identity-store-mapping>
                <identity-store-mapping>
                    <identity-store-id>LDAP Identity Store</identity-store-id>
                    <identity-object-types>
                        <identity-object-type>JBOSS_IDENTITY_GROUP_PEOPLE</identity-object-type>
                    </identity-object-types>
                    <options/>
                </identity-store-mapping>
            </identity-store-mappings>
        </repository>
    </repositories>
    <stores>
        <attribute-stores/>
        <identity-stores>
            <identity-store>
                <id>Hibernate Identity Store</id>
                <class>org.picketlink.idm.impl.store.hibernate.HibernateIdentityStoreImpl</class>
                <external-config/>
                <supported-relationship-types>
                    <relationship-type>JBOSS_IDENTITY_RELATIONSHIP_MEMBERSHIP</relationship-type>
                    <relationship-type>JBOSS_IDENTITY_RELATIONSHIP_ROLE</relationship-type>
                </supported-relationship-types>
                <supported-identity-object-types>
                    <identity-object-type>
                        <name>JBOSS_IDENTITY_IDENTITY</name>
                        <relationships/>
                        <attributes/>
                        <options/>
                    </identity-object-type>
                    <identity-object-type>
                        <name>JBOSS_IDENTITY_GROUP</name>
                        <relationships>
                            <relationship>
                                <relationship-type-ref>JBOSS_IDENTITY_RELATIONSHIP_MEMBERSHIP</relationship-type-ref>
                                <identity-object-type-ref>JBOSS_IDENTITY_IDENTITY</identity-object-type-ref>
                            </relationship>
                        </relationships>
                        <attributes/>
                        <options/>
                    </identity-object-type>
                </supported-identity-object-types>
                <options/>

            </identity-store>
            <identity-store>
                <id>LDAP Identity Store</id>
                <class>org.picketlink.idm.impl.store.hibernate.HibernateIdentityStoreImpl</class>
                <external-config override="false">path/to/file.xml</external-config>
                <supported-relationship-types>
                    <relationship-type>JBOSS_IDENTITY_RELATIONSHIP_MEMBERSHIP</relationship-type>
                    <relationship-type>JBOSS_IDENTITY_RELATIONSHIP_ROLE</relationship-type>
                </supported-relationship-types>
                <supported-identity-object-types>
                    <identity-object-type>
                        <name>JBOSS_IDENTITY_IDENTITY</name>
                        <relationships/>
                        <credentials/>
                        <attributes>
                            <attribute>
                                <name>user.name.given</name>
                                <type>text</type>
                                <mapping/>
                                <isRequired>false</isRequired>
                                <isMultivalued>true</isMultivalued>
                            </attribute>
                            <attribute>
                                <name>user.name.family</name>
                                <mapping/>
                                <isRequired>false</isRequired>
                                <isMultivalued>true</isMultivalued>
                            </attribute>
                        </attributes>
                        <options/>
                    </identity-object-type>
                    <identity-object-type>
                        <name>JBOSS_IDENTITY_GROUP_ORGANIZATION</name>
                        <relationships>
                            <relationship>
                                <relationship-type-ref>JBOSS_IDENTITY_RELATIONSHIP_MEMBERSHIP</relationship-type-ref>
                                <identity-object-type-ref>JBOSS_IDENTITY_IDENTITY</identity-object-type-ref>
                            </relationship>
                        </relationships>
                        <attributes>
                            <attribute>
                                <name>user.name.given</name>
                                <mapping/>
                                <isRequired>false</isRequired>
                                <isMultivalued>true</isMultivalued>
                            </attribute>
                            <attribute>
                                <name>user.name.family</name>
                                <mapping/>
                                <isRequired>false</isRequired>
                                <isMultivalued>true</isMultivalued>
                            </attribute>
                        </attributes>
                        <options/>
                    </identity-object-type>
                </supported-identity-object-types>
                <options/>
                <!--<options>-->
                <!--<option>-->
                <!--<name></name>-->
                <!--<values>-->
                <!--<value></value>-->
                <!--</values>-->
                <!--</option>-->
                <!--</options>-->
            </identity-store>
        </identity-stores>
    </stores>
</jboss-identity>

=== anilsaldhana/picketlink-idm/1.1.0/picketlink-idm-testsuite/src/test/resources/minimal-flexible-identity-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<jboss-identity xmlns="urn:picketlink:idm:config:v1_0_0_ga"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xsi:schemaLocation="urn:picketlink:idm:config:v1_0_0_ga identity-config.xsd">
   <realms>
      <realm>
         <id>realm://FlexibleRealm</id>
         <repository-id-ref>Flexible Repo</repository-id-ref>
         <identity-type-mappings>
            <user-mapping>USER</user-mapping>
         </identity-type-mappings>
      </realm>
   </realms>
   <repositories>
      <repository>
         <id>Flexible Repo</id>
         <class>org.picketlink.idm.impl.repository.WrapperIdentityStoreRepository</class>
         <external-config/>
         <default-identity-store-id>Hibernate Identity Store</default-identity-store-id>
         <default-attribute-store-id>Hibernate Identity Store</default-attribute-store-id>
         <options>
            <option>
               <name>allowNotDefinedAttributes</name>
               <value>true</value>
            </option>
            <option>
               <name>allowNotDefinedIdentityObjectTypes</name>
               <value>true</value>
            </option>
         </options>
      </repository>
   </repositories>
   <stores>
      <attribute-stores/>
      <identity-stores>
         <identity-store>
            <id>Hibernate Identity Store</id>
            <class>org.picketlink.idm.impl.store.hibernate.HibernateIdentityStoreImpl</class>
            <external-config/>
            <supported-relationship-types>
               <relationship-type>JBOSS_IDENTITY_MEMBERSHIP</relationship-type>
               <relationship-type>JBOSS_IDENTITY_ROLE</relationship-type>
            </supported-relationship-types>
            <supported-identity-object-types>
               <identity-object-type>
                  <name>USER</name>
                  <relationships/>
                  <credentials/>
                  <attributes>
                     <attribute>
                        <name>description</name>
                        <mapping>description</mapping>
                        <type>text</type>
                        <isRequired>false</isRequired>
                        <isMultivalued>false</isMultivalued>
                        <isReadOnly>true</isReadOnly>
                     </attribute>
                  </attributes>
                  <options/>
               </identity-object-type>
            </supported-identity-object-types>
            <options>
               <option>
                  <name>hibernateSessionFactoryJNDIName</name>
                  <value>java:/jbossidentity/HibernateStoreSessionFactory</value>
               </option>
               <option>
                  <name>populateRelationshipTypes</name>
                  <value>true</value>
               </option>
               <option>
                  <name>populateIdentityObjectTypes</name>
                  <value>true</value>
               </option>
               <option>
                  <name>isRealmAware</name>
                  <value>true</value>
               </option>
               <option>
                  <name>allowNotDefinedAttributes</name>
                  <value>true</value>
               </option>
               <option>
                  <name>allowNotDefinedIdentityObjectTypes</name>
                  <value>true</value>
               </option>
            </options>
         </identity-store>
      </identity-stores>
   </stores>
</jboss-identity>
